### ISSUE TITLE
I can not install your package.

### ISSUE THREAD

**Issue by raffdoc** [quantide/mapIT#4]
Here the error when I try to install you package using install_github() function

'''
Error in namespaceExport(ns, exports) : undefined exports: imap
Error: loading failed
Execution halted
'''

How can I fix this?

**Comment by nicolasturaro** [comment]
I fixed the bug. Please try again.

**Comment by andreaspano** [comment]
'diI HAVE fixed the buf RIGHT NOW
I fixed the bug LAST YEAR ,,,
non e' difficile .. vero !!

On 20 January 2015 at 22:30, Nicola Sturaro Sommacal <
notifications@github.com> wrote:

> I fixed the bug. Please try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quantide/mapIT/issues/4#issuecomment-70737581>.
>



-- 
Andrea Spanò
mobile: (+39) 347 747 04 92
e-mail: andrea.spano@quantide.co <andrea.spano@quantide.com>m

-- 

*Quantide srl*
Via Lepetit, 8
20124 Milano, Italy
office: (+39) 02 006 963 93
www.quantide.com

This electronic mail transmission may contain confidential information 
addressed only to the person (s) named. Any use, distribution, copying or 
disclosure by any other person and/or entities other than the intended 
recipient is prohibited. If you received this transmission in error, please 
inform the sender immediately and delete the material. 

Please consider the environment before printing.
